### ISSUE TITLE
Vulkan?

### ISSUE THREAD

**Issue by Starkium** [StinkySteak/unity-birp-vs-urp-benchmark#1]
Should probably test vulkan as well, no?

**Comment by StinkySteak** [comment]
Will try, I'm still omw to re-create the benchmark with free assets, thus I can just put the project open source.
The reason I didnt use Vulkan on my device is because Vulkan is faulty on Android 10 (recently discover), Upgrading to android 11 I gain 1.5x perf.

Also several old device doesnt really well on vulkan (glitchy)
